const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Behaviors.shadowcaster,
		C3.Plugins.List,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Behaviors.MoveTo,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Json.Exps.Get,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.urlencode,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Acts.Reverse,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.PickByComparison
	];
};
self.C3_JsPropNameTable = [
	{bx: 0},
	{WhiteBag: 0},
	{SkipBin: 0},
	{GreenGreyBag: 0},
	{GlassBin: 0},
	{BlackBag: 0},
	{AllBins: 0},
	{Sprite2: 0},
	{a: 0},
	{crX: 0},
	{crY: 0},
	{DragDrop: 0},
	{Fade: 0},
	{Tween: 0},
	{appleHalf_NE: 0},
	{bacon_NE: 0},
	{banana_NE: 0},
	{bottleKetchup_NE: 0},
	{canOpen_NE: 0},
	{carrot_NE: 0},
	{chocolateWrapper_NE: 0},
	{ciggarettebud: 0},
	{fishBones_NE: 0},
	{friesEmpty_NE: 0},
	{hotDog_NE: 0},
	{itemName: 0},
	{newspaper: 0},
	{paper_bag_NE: 0},
	{plastic_bag: 0},
	{plastic_bottle: 0},
	{plastic_bottle_2: 0},
	{soda_NE: 0},
	{sodaBottle_NE: 0},
	{sodaCan_NE: 0},
	{sodaCanCrushed_NE: 0},
	{utensilFork_NE: 0},
	{utensilKnife_NE: 0},
	{wineWhite_NE: 0},
	{ItemName: 0},
	{malteseName: 0},
	{englishName: 0},
	{zoomX: 0},
	{zoomY: 0},
	{originX: 0},
	{originY: 0},
	{Sine: 0},
	{aa: 0},
	{instanceId: 0},
	{Pin: 0},
	{GlowingBG: 0},
	{bground: 0},
	{bin: 0},
	{trash: 0},
	{option: 0},
	{righ: 0},
	{sound: 0},
	{title: 0},
	{playbtn: 0},
	{Audio: 0},
	{Touch: 0},
	{finish: 0},
	{square: 0},
	{Text: 0},
	{home: 0},
	{instruction: 0},
	{BlackBG: 0},
	{english: 0},
	{maltese: 0},
	{Text2: 0},
	{nameInput: 0},
	{OkButton: 0},
	{englishMenu: 0},
	{malteseMenu: 0},
	{englishGame: 0},
	{malteseGame: 0},
	{Text3: 0},
	{QuestionText: 0},
	{RightAnswer: 0},
	{Option1: 0},
	{Option2: 0},
	{Option3: 0},
	{AJAX: 0},
	{JSON: 0},
	{Browser: 0},
	{OptionButtonNumber: 0},
	{OptionButton: 0},
	{Type: 0},
	{Buttons: 0},
	{timer: 0},
	{ScoreText: 0},
	{Border: 0},
	{BG: 0},
	{GameTitleText: 0},
	{BeachObject: 0},
	{RecyclableWasteText: 0},
	{Text6: 0},
	{GameOverText: 0},
	{Text7: 0},
	{PointText: 0},
	{Background: 0},
	{Settings: 0},
	{pause: 0},
	{Background2: 0},
	{Sprite3: 0},
	{squer: 0},
	{Sprite4: 0},
	{ShadowCaster: 0},
	{Icons: 0},
	{buttonNumber: 0},
	{rect: 0},
	{LatterBG: 0},
	{MusicIcon: 0},
	{SoundIcon: 0},
	{LatterObjectCount: 0},
	{English: 0},
	{PlayText: 0},
	{Trashhunterlogo: 0},
	{Button: 0},
	{List: 0},
	{Sprite: 0},
	{Text4: 0},
	{ScoreTextGameOver: 0},
	{TimerGameOver: 0},
	{OkButtonGameover: 0},
	{OkTextGameOver: 0},
	{square2: 0},
	{StartsCompletion: 0},
	{savingourblue: 0},
	{triviachallenge: 0},
	{PeoplePlayingVolleyball2x: 0},
	{BeachResting2x: 0},
	{PersonWithSkateboard2x: 0},
	{ManDrinking: 0},
	{people: 0},
	{BeachMat: 0},
	{savingoutbluelogo: 0},
	{hand: 0},
	{LevelFinishOk: 0},
	{statue: 0},
	{boat: 0},
	{SOBicons: 0},
	{ScoreboardItemsDisposedCorrectly: 0},
	{ScoreboardItemsDisposedWrongly: 0},
	{ScoreboardQuizBonus: 0},
	{smallStar2x: 0},
	{bigStar2x: 0},
	{LocationName: 0},
	{seashell: 0},
	{twitter: 0},
	{guardiolatower: 0},
	{beachsand2x: 0},
	{MaltaTemples: 0},
	{icon: 0},
	{LocalStorage: 0},
	{HighsCores: 0},
	{LeaderBoard: 0},
	{TextInput: 0},
	{Text8: 0},
	{facebook: 0},
	{boat2x: 0},
	{maggie: 0},
	{WellDoneText: 0},
	{gameover: 0},
	{isGameOver: 0},
	{MoveTo: 0},
	{speechbubble: 0},
	{Particles: 0},
	{Keyboard: 0},
	{MEEELogo: 0},
	{Text9: 0},
	{englilsh: 0},
	{GamePausedText: 0},
	{winEnglish: 0},
	{winMaltese: 0},
	{loseEnglish: 0},
	{loseMaltese: 0},
	{QuizResultText: 0},
	{QuizResultBG: 0},
	{QuizResultsBG: 0},
	{Invisible: 0},
	{Maltese: 0},
	{EnglishText: 0},
	{MalteseText: 0},
	{ResetZoom: 0},
	{ResetZoomText: 0},
	{Language: 0},
	{LanguageText: 0},
	{GlassWasteText: 0},
	{OrganicWasteText: 0},
	{ElectronicWasteText: 0},
	{ResidualWasteText: 0},
	{CASite: 0},
	{url: 0},
	{Button2: 0},
	{GameName: 0},
	{Text5: 0},
	{OpenURL: 0},
	{AnswerSymbol: 0},
	{Mouse: 0},
	{HintBG: 0},
	{HintText: 0},
	{HintArrow: 0},
	{FullScreenWarning: 0},
	{OkButton2: 0},
	{OkTextFullScreenWarning: 0},
	{FullScreenWarningBG: 0},
	{TriviaTimer: 0},
	{varm: 0},
	{RightAnswerFromTheJSON: 0},
	{ChooseQuestion: 0},
	{IsTouchedButton: 0},
	{GameStart: 0},
	{Timer: 0},
	{StartTime: 0},
	{LatterObjectWidth: 0},
	{LatterObjectHeight: 0},
	{ScaleValue: 0},
	{SoundOnOff: 0},
	{Hint: 0},
	{zoomScale: 0},
	{wrongItemDisposed: 0},
	{correctItemDisposed: 0},
	{quizbonuspoints: 0},
	{TimerText: 0},
	{startDistance: 0},
	{startScale: 0},
	{dragNewPositionX: 0},
	{dragNewPositionY: 0},
	{dragPreviousPositionX: 0},
	{dragPreviousPositionY: 0},
	{dragRangeX: 0},
	{dragRangeY: 0},
	{dragDistanceX: 0},
	{dragDistanceY: 0},
	{dragDeltaX: 0},
	{dragDeltaY: 0},
	{exCount: 0},
	{questionGenerated: 0},
	{hintGiven: 0},
	{AddSparkle: 0},
	{TriggerGlowingEffectTimer: 0},
	{ZoomInsideBound: 0},
	{mini: 0},
	{sec: 0},
	{milisec: 0},
	{newScale: 0},
	{PlayerName: 0},
	{selecteddidYouKnow: 0},
	{FontSizeLevel: 0},
	{ChoseEnglish: 0},
	{ColorBlind: 0},
	{iPhone: 0},
	{factDisplayed: 0},
	{isPc: 0},
	{Score: 0},
	{web_app_url: 0},
	{highscores: 0},
	{s: 0},
	{name: 0},
	{score: 0},
	{varm2: 0},
	{RightAnswerFromTheJSON2: 0},
	{ChooseQuestion2: 0},
	{IsTouchedButton2: 0},
	{GameStart2: 0},
	{Timer2: 0},
	{StartTime2: 0},
	{LatterObjectWidth2: 0},
	{LatterObjectHeight2: 0},
	{ScaleValue2: 0},
	{SoundOnOff2: 0},
	{LatterObjectCount2: 0},
	{Hint2: 0},
	{zoomScale2: 0},
	{wrongItemDisposed2: 0},
	{correctItemDisposed2: 0},
	{quizbonuspoints2: 0},
	{TimerText2: 0},
	{varm3: 0},
	{RightAnswerFromTheJSON3: 0},
	{ChooseQuestion3: 0},
	{IsTouchedButton3: 0},
	{GameStart3: 0},
	{Timer3: 0},
	{StartTime3: 0},
	{LatterObjectWidth3: 0},
	{LatterObjectHeight3: 0},
	{ScaleValue3: 0},
	{SoundOnOff3: 0},
	{LatterObjectCount3: 0},
	{Hint3: 0},
	{zoomScale3: 0},
	{wrongItemDisposed3: 0},
	{correctItemDisposed3: 0},
	{quizbonuspoints3: 0},
	{TimerText3: 0},
	{varm4: 0},
	{RightAnswerFromTheJSON4: 0},
	{ChooseQuestion4: 0},
	{IsTouchedButton4: 0},
	{GameStart4: 0},
	{Timer4: 0},
	{StartTime4: 0},
	{LatterObjectWidth4: 0},
	{LatterObjectHeight4: 0},
	{ScaleValue4: 0},
	{SoundOnOff4: 0},
	{LatterObjectCount4: 0},
	{Hint4: 0},
	{zoomScale4: 0},
	{wrongItemDisposed4: 0},
	{correctItemDisposed4: 0},
	{quizbonuspoints4: 0},
	{TimerText4: 0},
	{varm5: 0},
	{RightAnswerFromTheJSON5: 0},
	{ChooseQuestion5: 0},
	{IsTouchedButton5: 0},
	{GameStart5: 0},
	{Timer5: 0},
	{StartTime5: 0},
	{LatterObjectWidth5: 0},
	{LatterObjectHeight5: 0},
	{ScaleValue5: 0},
	{SoundOnOff5: 0},
	{LatterObjectCount5: 0},
	{Hint5: 0},
	{zoomScale5: 0},
	{wrongItemDisposed5: 0},
	{correctItemDisposed5: 0},
	{quizbonuspoints5: 0},
	{TimerText5: 0},
	{varm6: 0},
	{RightAnswerFromTheJSON6: 0},
	{ChooseQuestion6: 0},
	{IsTouchedButton6: 0},
	{GameStart6: 0},
	{Timer6: 0},
	{StartTime6: 0},
	{LatterObjectWidth6: 0},
	{LatterObjectHeight6: 0},
	{ScaleValue6: 0},
	{SoundOnOff6: 0},
	{LatterObjectCount6: 0},
	{Hint6: 0},
	{zoomScale6: 0},
	{wrongItemDisposed6: 0},
	{correctItemDisposed6: 0},
	{quizbonuspoints6: 0},
	{TimerText6: 0},
	{varm7: 0},
	{RightAnswerFromTheJSON7: 0},
	{ChooseQuestion7: 0},
	{IsTouchedButton7: 0},
	{GameStart7: 0},
	{Timer7: 0},
	{StartTime7: 0},
	{LatterObjectWidth7: 0},
	{LatterObjectHeight7: 0},
	{ScaleValue7: 0},
	{SoundOnOff7: 0},
	{LatterObjectCount7: 0},
	{Hint7: 0},
	{zoomScale7: 0},
	{wrongItemDisposed7: 0},
	{correctItemDisposed7: 0},
	{quizbonuspoints7: 0},
	{TimerText7: 0},
	{varm8: 0},
	{RightAnswerFromTheJSON8: 0},
	{ChooseQuestion8: 0},
	{IsTouchedButton8: 0},
	{GameStart8: 0},
	{Timer8: 0},
	{StartTime8: 0},
	{LatterObjectWidth8: 0},
	{LatterObjectHeight8: 0},
	{ScaleValue8: 0},
	{SoundOnOff8: 0},
	{LatterObjectCount8: 0},
	{Hint8: 0},
	{zoomScale8: 0},
	{wrongItemDisposed8: 0},
	{correctItemDisposed8: 0},
	{quizbonuspoints8: 0},
	{TimerText8: 0},
	{varm9: 0},
	{RightAnswerFromTheJSON9: 0},
	{ChooseQuestion9: 0},
	{IsTouchedButton9: 0},
	{GameStart9: 0},
	{Timer9: 0},
	{StartTime9: 0},
	{LatterObjectWidth9: 0},
	{LatterObjectHeight9: 0},
	{ScaleValue9: 0},
	{SoundOnOff9: 0},
	{LatterObjectCount9: 0},
	{Hint9: 0},
	{zoomScale9: 0},
	{wrongItemDisposed9: 0},
	{correctItemDisposed9: 0},
	{quizbonuspoints9: 0},
	{TimerText9: 0},
	{GloabalFontSize: 0}
];

self.InstanceType = {
	WhiteBag: class extends self.ISpriteInstance {},
	SkipBin: class extends self.ISpriteInstance {},
	GreenGreyBag: class extends self.ISpriteInstance {},
	GlassBin: class extends self.ISpriteInstance {},
	BlackBag: class extends self.ISpriteInstance {},
	AllBins: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	appleHalf_NE: class extends self.ISpriteInstance {},
	bacon_NE: class extends self.ISpriteInstance {},
	banana_NE: class extends self.ISpriteInstance {},
	bottleKetchup_NE: class extends self.ISpriteInstance {},
	canOpen_NE: class extends self.ISpriteInstance {},
	carrot_NE: class extends self.ISpriteInstance {},
	chocolateWrapper_NE: class extends self.ISpriteInstance {},
	ciggarettebud: class extends self.ISpriteInstance {},
	fishBones_NE: class extends self.ISpriteInstance {},
	friesEmpty_NE: class extends self.ISpriteInstance {},
	hotDog_NE: class extends self.ISpriteInstance {},
	newspaper: class extends self.ISpriteInstance {},
	paper_bag_NE: class extends self.ISpriteInstance {},
	plastic_bag: class extends self.ISpriteInstance {},
	plastic_bottle: class extends self.ISpriteInstance {},
	plastic_bottle_2: class extends self.ISpriteInstance {},
	soda_NE: class extends self.ISpriteInstance {},
	sodaBottle_NE: class extends self.ISpriteInstance {},
	sodaCan_NE: class extends self.ISpriteInstance {},
	sodaCanCrushed_NE: class extends self.ISpriteInstance {},
	utensilFork_NE: class extends self.ISpriteInstance {},
	utensilKnife_NE: class extends self.ISpriteInstance {},
	wineWhite_NE: class extends self.ISpriteInstance {},
	aa: class extends self.ISpriteInstance {},
	GlowingBG: class extends self.ISpriteInstance {},
	bground: class extends self.ISpriteInstance {},
	bin: class extends self.ISpriteInstance {},
	trash: class extends self.ISpriteInstance {},
	righ: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	playbtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	finish: class extends self.ISpriteInstance {},
	square: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	home: class extends self.ISpriteInstance {},
	instruction: class extends self.ISpriteInstance {},
	BlackBG: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	nameInput: class extends self.ITextInputInstance {},
	OkButton: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	QuestionText: class extends self.ITextInstance {},
	Option1: class extends self.ITextInstance {},
	Option2: class extends self.ITextInstance {},
	Option3: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	OptionButton: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	Border: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	GameTitleText: class extends self.ITextInstance {},
	BeachObject: class extends self.ISpriteInstance {},
	RecyclableWasteText: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	GameOverText: class extends self.ITextInstance {},
	ItemName: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	PointText: class extends self.ITextInstance {},
	Background: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	squer: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	rect: class extends self.ISpriteInstance {},
	LatterBG: class extends self.ISpriteInstance {},
	MusicIcon: class extends self.ISpriteInstance {},
	SoundIcon: class extends self.ISpriteInstance {},
	LatterObjectCount: class extends self.ITextInstance {},
	PlayText: class extends self.ITextInstance {},
	Trashhunterlogo: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	List: class extends self.IListInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	ScoreTextGameOver: class extends self.ITextInstance {},
	TimerGameOver: class extends self.ITextInstance {},
	OkButtonGameover: class extends self.ISpriteInstance {},
	OkTextGameOver: class extends self.ITextInstance {},
	square2: class extends self.ISpriteInstance {},
	StartsCompletion: class extends self.ISpriteInstance {},
	savingourblue: class extends self.ISpriteInstance {},
	triviachallenge: class extends self.ISpriteInstance {},
	PeoplePlayingVolleyball2x: class extends self.ISpriteInstance {},
	BeachResting2x: class extends self.ISpriteInstance {},
	PersonWithSkateboard2x: class extends self.ISpriteInstance {},
	ManDrinking: class extends self.ISpriteInstance {},
	people: class extends self.ISpriteInstance {},
	BeachMat: class extends self.ISpriteInstance {},
	savingoutbluelogo: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	LevelFinishOk: class extends self.ISpriteInstance {},
	statue: class extends self.ISpriteInstance {},
	boat: class extends self.ISpriteInstance {},
	SOBicons: class extends self.ISpriteInstance {},
	ScoreboardItemsDisposedCorrectly: class extends self.ITextInstance {},
	ScoreboardItemsDisposedWrongly: class extends self.ITextInstance {},
	ScoreboardQuizBonus: class extends self.ITextInstance {},
	smallStar2x: class extends self.ISpriteInstance {},
	bigStar2x: class extends self.ISpriteInstance {},
	LocationName: class extends self.ITextInstance {},
	seashell: class extends self.ISpriteInstance {},
	twitter: class extends self.ISpriteInstance {},
	guardiolatower: class extends self.ISpriteInstance {},
	beachsand2x: class extends self.ISpriteInstance {},
	MaltaTemples: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	HighsCores: class extends self.IArrayInstance {},
	LeaderBoard: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Text8: class extends self.ITextInstance {},
	facebook: class extends self.ISpriteInstance {},
	boat2x: class extends self.ISpriteInstance {},
	maggie: class extends self.ISpriteInstance {},
	WellDoneText: class extends self.ITextInstance {},
	speechbubble: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Keyboard: class extends self.IInstance {},
	MEEELogo: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	GamePausedText: class extends self.ITextInstance {},
	QuizResultText: class extends self.ITextInstance {},
	QuizResultBG: class extends self.ISpriteInstance {},
	QuizResultsBG: class extends self.ISpriteInstance {},
	Invisible: class extends self.ISpriteInstance {},
	English: class extends self.ISpriteInstance {},
	Maltese: class extends self.ISpriteInstance {},
	EnglishText: class extends self.ITextInstance {},
	MalteseText: class extends self.ITextInstance {},
	ResetZoom: class extends self.ISpriteInstance {},
	ResetZoomText: class extends self.ITextInstance {},
	Language: class extends self.ISpriteInstance {},
	LanguageText: class extends self.ITextInstance {},
	GlassWasteText: class extends self.ITextInstance {},
	OrganicWasteText: class extends self.ITextInstance {},
	ElectronicWasteText: class extends self.ITextInstance {},
	ResidualWasteText: class extends self.ITextInstance {},
	CASite: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	GameName: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	OpenURL: class extends self.ISpriteInstance {},
	AnswerSymbol: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	HintBG: class extends self.ISpriteInstance {},
	HintText: class extends self.ITextInstance {},
	HintArrow: class extends self.ISpriteInstance {},
	FullScreenWarning: class extends self.ITextInstance {},
	OkButton2: class extends self.ISpriteInstance {},
	OkTextFullScreenWarning: class extends self.ITextInstance {},
	FullScreenWarningBG: class extends self.ISpriteInstance {},
	TriviaTimer: class extends self.ITextInstance {}
}